spring:
  application:
    name: service-registry-ms
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8761

